class TokenFactory(object):
    def isValid(token):
        raise NotImplementedError
    def create(claims):
        raise NotImplementedError
    def create():
        raise NotImplementedError
    def decode(token):
        raise NotImplementedError
